title: Mojo + Computational Economics
author: QuantEcon Developer Team
logo: _static/qe-logo.png
description: This website is an experimental review of Mojo (Modular) to evaluate real-world speed gains

execute:
  execute_notebooks: "cache"
  timeout: 600 # 10 minutes

html:
  baseurl: https://mojo.quantecon.org/

latex:
  latex_documents:
     targetname: quantecon-mojo.tex

sphinx:
  # extra_extensions: [sphinxext.rediraffe, sphinx_tojupyter, sphinx_exercise, sphinx_togglebutton]
  config:
    html_favicon: _static/lectures-favicon.ico
    html_theme: quantecon_book_theme
    html_static_path: ['_static']
    html_theme_options:
      dark_logo: quantecon-logo-transparent.png
      header_organisation_url: https://quantecon.org
      header_organisation: QuantEcon
      repository_url: https://github.com/QuantEcon/project.lecture-mojo
      # nb_repository_url: https://github.com/QuantEcon/lecture-python-programming.notebooks
      twitter: quantecon
      twitter_logo_url: https://assets.quantecon.org/img/qe-twitter-logo.png
      og_logo_url: https://assets.quantecon.org/img/qe-og-logo.png
      description: This website is an experimental review of Mojo (Modular) to evaluate real-world speed gains
      keywords: Python, QuantEcon, Quantitative Economics, Economics, Mojo
      # analytics:
      #   google_analytics_id: G-X7DH1M2DPY
      # launch_buttons:
      #   notebook_interface        : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
      #   colab_url                 : https://colab.research.google.com
      #   thebe                     : false  # Add a thebe button to pages (requires the repository to run on Binder)
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    # rediraffe_redirects:
    #   index_toc.md: intro.md
    # tojupyter_static_file_path: ["source/_static", "_static"]
    # tojupyter_target_html: true
    # tojupyter_urlpath: "https://mojo.quantecon.org/"
    # tojupyter_image_urlpath: "https://mojo.quantecon.org/_static/"
    # tojupyter_lang_synonyms: ["ipython", "ipython3", "python"]
    # tojupyter_kernels:
    #   python3:
    #     kernelspec:
    #       display_name: "Python"
    #       language: python3
    #       name: python3
    #     file_extension: ".py"
    # tojupyter_images_markdown: true
