name: Build and Publish to gh-pages
on: [push]
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Anaconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: true
          miniconda-version: 'latest'
          python-version: "3.11"
          environment-file: environment.yml
          activate-environment: quantecon
      - name: Install Mojo
        shell: bash -l {0}
        run: |
          curl https://get.modular.com | sh - && modular auth mut_5f23083ec92b43e39497b5414e2f2234
          modular install mojo
          export MODULAR_HOME="/home/runner/.modular"
          echo "/home/runner/.modular/pkg/packages.modular.com_mojo/bin:$PATH" >> $GITHUB_PATH
      - name: Display Conda Environment Versions
        shell: bash -l {0}
        run: conda list
      - name: Display Pip Versions
        shell: bash -l {0}
        run: pip list
      - name: Display Kernel list
        shell: bash -l {0}
        run: jupyter kernelspec list
      - name: Run Mojo
        shell: bash -l {0}
        run: |
          echo $GITHUB_PATH
          mojo hello.mojo
          mojo -v
      - name: Build HTML
        shell: bash -l {0}
        run: |
          jb build ./ --path-output ./
      - name: Upload Execution Reports
        uses: actions/upload-artifact@v2
        with:
          name: execution-reports
          path: _build/html/reports
      - name: Deploy website to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/html/
