name: Build and Publish to gh-pages
on: [push]
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Anaconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: true
          miniconda-version: 'latest'
          python-version: "3.11"
          environment-file: environment.yml
          activate-environment: quantecon
      - name: Install Mojo
        shell: bash -l {0}
        run: |
          curl https://get.modular.com | sh - && modular auth mut_6134c6e374c8475394a876f6d8eb9612
          modular install mojo
          echo "${HOME}/.modular/pkg/packages.modular.com_mojo/bin" >> $GITHUB_PATH
      - name: Display Conda Environment Versions
        shell: bash -l {0}
        run: conda list
      - name: Display Pip Versions
        shell: bash -l {0}
        run: pip list
      - name: Run Mojo
        shell: bash -l {0}
        run: |
          echo $GITHUB_PATH
          mojo hello.mojo
      - name: Build HTML
        shell: bash -l {0}
        run: |
          jb build ./ --path-output ./ -n -W --keep-going
      - name: Upload Execution Reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: execution-reports
          path: _build/html/reports
      - name: Deploy website to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/html/
